export const USER_STATUS_SECTION = 'USER_STATUS_SECTION';
export const USER_EXPIRED = 'USER_EXPIRED';
export const USER_INSPIRED = 'USER_INSPIRED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
